// ============================================================
// mandiData.ts — comprehensive database of Indian APMC mandi
// locations (city, district, state + mandi names) used by the
// Mandi Prices page, the dashboard ticker and the nearest-mandi
// widget. ~200 locations covering every major agricultural
// district across all states. Single source of truth.
// ============================================================

export interface MandiLocation {
  city: string;
  state: string;
  district: string;
  mandis: string[];
}

export const MANDI_LOCATIONS: MandiLocation[] = [
  // ---------- Delhi NCR ----------
  { city: "Delhi", state: "Delhi", district: "North Delhi", mandis: ["Azadpur Mandi", "Ghazipur Mandi"] },
  { city: "Delhi", state: "Delhi", district: "South Delhi", mandis: ["Okhla Mandi"] },
  { city: "Delhi", state: "Delhi", district: "South West Delhi", mandis: ["Najafgarh Mandi"] },
  { city: "Delhi", state: "Delhi", district: "East Delhi", mandis: ["Ghazipur Mandi", "Kondli Mandi"] },
  { city: "Noida", state: "Uttar Pradesh", district: "Gautam Buddha Nagar", mandis: ["Noida Sector Mandi"] },
  { city: "Greater Noida", state: "Uttar Pradesh", district: "Gautam Buddha Nagar", mandis: ["Dadri Mandi"] },
  { city: "Gurugram", state: "Haryana", district: "Gurugram", mandis: ["Gurugram Mandi", "Kadipur Mandi"] },
  { city: "Faridabad", state: "Haryana", district: "Faridabad", mandis: ["Faridabad Mandi"] },
  { city: "Ghaziabad", state: "Uttar Pradesh", district: "Ghaziabad", mandis: ["Ghaziabad Mandi", "Loni Mandi"] },

  // ---------- Western UP (incl. Bulandshahr belt) ----------
  { city: "Bulandshahr", state: "Uttar Pradesh", district: "Bulandshahr", mandis: ["Bulandshahr Mandi", "Khurja Mandi", "Sikandrabad Mandi"] },
  { city: "Hapur", state: "Uttar Pradesh", district: "Hapur", mandis: ["Hapur Mandi", "Pilkhuwa Mandi", "Dhaulana Mandi"] },
  { city: "Meerut", state: "Uttar Pradesh", district: "Meerut", mandis: ["Meerut Mandi", "Mawana Mandi", "Sardhana Mandi"] },
  { city: "Muzaffarnagar", state: "Uttar Pradesh", district: "Muzaffarnagar", mandis: ["Muzaffarnagar Mandi", "Budhana Mandi", "Charthawal Mandi"] },
  { city: "Shamli", state: "Uttar Pradesh", district: "Shamli", mandis: ["Shamli Mandi", "Kairana Mandi"] },
  { city: "Baghpat", state: "Uttar Pradesh", district: "Baghpat", mandis: ["Baghpat Mandi", "Baraut Mandi"] },
  { city: "Amroha", state: "Uttar Pradesh", district: "Amroha", mandis: ["Amroha Mandi", "Hasanpur Mandi"] },
  { city: "Bijnor", state: "Uttar Pradesh", district: "Bijnor", mandis: ["Bijnor Mandi", "Najibabad Mandi", "Chandpur Mandi"] },
  { city: "Moradabad", state: "Uttar Pradesh", district: "Moradabad", mandis: ["Moradabad Mandi", "Chandausi Mandi"] },
  { city: "Rampur", state: "Uttar Pradesh", district: "Rampur", mandis: ["Rampur Mandi", "Bilaspur Mandi"] },
  { city: "Sambhal", state: "Uttar Pradesh", district: "Sambhal", mandis: ["Sambhal Mandi", "Chandausi Mandi"] },
  { city: "Badaun", state: "Uttar Pradesh", district: "Budaun", mandis: ["Budaun Mandi", "Sahaswan Mandi"] },
  { city: "Bareilly", state: "Uttar Pradesh", district: "Bareilly", mandis: ["Bareilly Mandi", "Aonla Mandi", "Faridpur Mandi"] },
  { city: "Pilibhit", state: "Uttar Pradesh", district: "Pilibhit", mandis: ["Pilibhit Mandi", "Bisalpur Mandi"] },
  { city: "Shahjahanpur", state: "Uttar Pradesh", district: "Shahjahanpur", mandis: ["Shahjahanpur Mandi", "Tilhar Mandi"] },
  { city: "Aligarh", state: "Uttar Pradesh", district: "Aligarh", mandis: ["Aligarh Mandi", "Khair Mandi", "Atrauli Mandi"] },
  { city: "Hathras", state: "Uttar Pradesh", district: "Hathras", mandis: ["Hathras Mandi", "Sikandra Rao Mandi"] },
  { city: "Mathura", state: "Uttar Pradesh", district: "Mathura", mandis: ["Mathura Mandi", "Chhata Mandi", "Mant Mandi"] },
  { city: "Agra", state: "Uttar Pradesh", district: "Agra", mandis: ["Agra Mandi", "Sadar Bazaar Mandi", "Fatehpur Sikri Mandi"] },
  { city: "Firozabad", state: "Uttar Pradesh", district: "Firozabad", mandis: ["Firozabad Mandi", "Jasrana Mandi"] },
  { city: "Etah", state: "Uttar Pradesh", district: "Etah", mandis: ["Etah Mandi", "Kasganj Mandi"] },
  { city: "Kasganj", state: "Uttar Pradesh", district: "Kasganj", mandis: ["Kasganj Mandi", "Sorou Mandi"] },
  { city: "Mainpuri", state: "Uttar Pradesh", district: "Mainpuri", mandis: ["Mainpuri Mandi", "Bewar Mandi"] },
  { city: "Etawah", state: "Uttar Pradesh", district: "Etawah", mandis: ["Etawah Mandi", "Bharthana Mandi"] },
  { city: "Auraiya", state: "Uttar Pradesh", district: "Auraiya", mandis: ["Auraiya Mandi"] },
  { city: "Kanpur", state: "Uttar Pradesh", district: "Kanpur", mandis: ["Kanpur Mandi", "Jajmau Mandi", "Akbarpur Mandi"] },
  { city: "Kanpur Dehat", state: "Uttar Pradesh", district: "Kanpur Dehat", mandis: ["Akbarpur Mandi", "Rura Mandi"] },
  { city: "Unnao", state: "Uttar Pradesh", district: "Unnao", mandis: ["Unnao Mandi", "Bangarmau Mandi"] },
  { city: "Lucknow", state: "Uttar Pradesh", district: "Lucknow", mandis: ["Ghazipur Mandi Lucknow", "Aminabad Mandi", "Malihabad Mandi"] },
  { city: "Barabanki", state: "Uttar Pradesh", district: "Barabanki", mandis: ["Barabanki Mandi", "Ramnagar Mandi"] },
  { city: "Sitapur", state: "Uttar Pradesh", district: "Sitapur", mandis: ["Sitapur Mandi", "Laharpur Mandi"] },
  { city: "Hardoi", state: "Uttar Pradesh", district: "Hardoi", mandis: ["Hardoi Mandi", "Sandila Mandi"] },
  { city: "Lakhimpur", state: "Uttar Pradesh", district: "Lakhimpur Kheri", mandis: ["Lakhimpur Mandi", "Gola Gokarnnath Mandi"] },
  { city: "Raebareli", state: "Uttar Pradesh", district: "Raebareli", mandis: ["Raebareli Mandi", "Lalganj Mandi"] },
  { city: "Amethi", state: "Uttar Pradesh", district: "Amethi", mandis: ["Amethi Mandi", "Gauriganj Mandi"] },
  { city: "Sultanpur", state: "Uttar Pradesh", district: "Sultanpur", mandis: ["Sultanpur Mandi", "Kadipur Mandi"] },
  { city: "Pratapgarh", state: "Uttar Pradesh", district: "Pratapgarh", mandis: ["Pratapgarh Mandi", "Kunda Mandi"] },
  { city: "Allahabad", state: "Uttar Pradesh", district: "Prayagraj", mandis: ["Allahabad APMC", "Handia Mandi"] },
  { city: "Kaushambi", state: "Uttar Pradesh", district: "Kaushambi", mandis: ["Manjhanpur Mandi"] },
  { city: "Fatehpur", state: "Uttar Pradesh", district: "Fatehpur", mandis: ["Fatehpur Mandi", "Bindki Mandi"] },
  { city: "Varanasi", state: "Uttar Pradesh", district: "Varanasi", mandis: ["Varanasi Mandi", "Bhadohi Mandi", "Pindra Mandi"] },
  { city: "Chandauli", state: "Uttar Pradesh", district: "Chandauli", mandis: ["Chandauli Mandi", "Sakaldaha Mandi"] },
  { city: "Mirzapur", state: "Uttar Pradesh", district: "Mirzapur", mandis: ["Mirzapur Mandi", "Lalganj Mandi"] },
  { city: "Sonbhadra", state: "Uttar Pradesh", district: "Sonbhadra", mandis: ["Robertsganj Mandi"] },
  { city: "Ghazipur", state: "Uttar Pradesh", district: "Ghazipur", mandis: ["Ghazipur Mandi", "Zamania Mandi"] },
  { city: "Ballia", state: "Uttar Pradesh", district: "Ballia", mandis: ["Ballia Mandi", "Rasra Mandi"] },
  { city: "Deoria", state: "Uttar Pradesh", district: "Deoria", mandis: ["Deoria Mandi", "Salempur Mandi"] },
  { city: "Kushinagar", state: "Uttar Pradesh", district: "Kushinagar", mandis: ["Padrauna Mandi"] },
  { city: "Gorakhpur", state: "Uttar Pradesh", district: "Gorakhpur", mandis: ["Gorakhpur Mandi", "Campierganj Mandi"] },
  { city: "Azamgarh", state: "Uttar Pradesh", district: "Azamgarh", mandis: ["Azamgarh Mandi", "Lalganj Mandi"] },
  { city: "Mau", state: "Uttar Pradesh", district: "Mau", mandis: ["Mau Mandi", "Ghosi Mandi"] },
  { city: "Jaunpur", state: "Uttar Pradesh", district: "Jaunpur", mandis: ["Jaunpur Mandi", "Kerakat Mandi"] },
  { city: "Basti", state: "Uttar Pradesh", district: "Basti", mandis: ["Basti Mandi", "Harraiya Mandi"] },
  { city: "Gonda", state: "Uttar Pradesh", district: "Gonda", mandis: ["Gonda Mandi", "Mankapur Mandi"] },
  { city: "Bahraich", state: "Uttar Pradesh", district: "Bahraich", mandis: ["Bahraich Mandi", "Nanpara Mandi"] },
  { city: "Shravasti", state: "Uttar Pradesh", district: "Shravasti", mandis: ["Bhinga Mandi"] },
  { city: "Balrampur", state: "Uttar Pradesh", district: "Balrampur", mandis: ["Balrampur Mandi", "Tulsipur Mandi"] },
  { city: "Siddharthnagar", state: "Uttar Pradesh", district: "Siddharthnagar", mandis: ["Naugarh Mandi"] },
  { city: "Maharajganj", state: "Uttar Pradesh", district: "Maharajganj", mandis: ["Maharajganj Mandi", "Nautanwa Mandi"] },
  { city: "Jhansi", state: "Uttar Pradesh", district: "Jhansi", mandis: ["Jhansi Mandi", "Mauranipur Mandi"] },
  { city: "Lalitpur", state: "Uttar Pradesh", district: "Lalitpur", mandis: ["Lalitpur Mandi"] },
  { city: "Banda", state: "Uttar Pradesh", district: "Banda", mandis: ["Banda Mandi", "Naraini Mandi"] },
  { city: "Hamirpur", state: "Uttar Pradesh", district: "Hamirpur", mandis: ["Hamirpur Mandi", "Rath Mandi"] },
  { city: "Mahoba", state: "Uttar Pradesh", district: "Mahoba", mandis: ["Mahoba Mandi"] },
  { city: "Chitrakoot", state: "Uttar Pradesh", district: "Chitrakoot", mandis: ["Karwi Mandi"] },
  { city: "Bijnor City", state: "Uttar Pradesh", district: "Bijnor", mandis: ["Kiratpur Mandi"] },
  { city: "Orai", state: "Uttar Pradesh", district: "Jalaun", mandis: ["Orai Mandi", "Konch Mandi"] },
  { city: "Jalaun", state: "Uttar Pradesh", district: "Jalaun", mandis: ["Kalpi Mandi"] },

  // ---------- Uttarakhand ----------
  { city: "Dehradun", state: "Uttarakhand", district: "Dehradun", mandis: ["Dehradun Mandi", "Vikasnagar Mandi"] },
  { city: "Haridwar", state: "Uttarakhand", district: "Haridwar", mandis: ["Haridwar Mandi", "Roorkee Mandi"] },
  { city: "Rudrapur", state: "Uttarakhand", district: "Udham Singh Nagar", mandis: ["Rudrapur Mandi", "Kichha Mandi"] },
  { city: "Haldwani", state: "Uttarakhand", district: "Nainital", mandis: ["Haldwani Mandi"] },
  { city: "Kashipur", state: "Uttarakhand", district: "Udham Singh Nagar", mandis: ["Kashipur Mandi"] },
  { city: "Pauri", state: "Uttarakhand", district: "Pauri Garhwal", mandis: ["Kotdwar Mandi"] },

  // ---------- Punjab ----------
  { city: "Ludhiana", state: "Punjab", district: "Ludhiana", mandis: ["Ludhiana Mandi", "Khanna Mandi", "Jagraon Mandi"] },
  { city: "Amritsar", state: "Punjab", district: "Amritsar", mandis: ["Amritsar Mandi", "Jandiala Guru Mandi"] },
  { city: "Jalandhar", state: "Punjab", district: "Jalandhar", mandis: ["Jalandhar Mandi", "Nakodar Mandi"] },
  { city: "Patiala", state: "Punjab", district: "Patiala", mandis: ["Patiala Mandi", "Rajpura Mandi", "Samana Mandi"] },
  { city: "Bathinda", state: "Punjab", district: "Bathinda", mandis: ["Bathinda Mandi", "Rampura Mandi"] },
  { city: "Sangrur", state: "Punjab", district: "Sangrur", mandis: ["Sangrur Mandi", "Dhuri Mandi", "Sunam Mandi"] },
  { city: "Mansa", state: "Punjab", district: "Mansa", mandis: ["Mansa Mandi", "Budhlada Mandi"] },
  { city: "Firozpur", state: "Punjab", district: "Firozpur", mandis: ["Firozpur Mandi", "Zira Mandi"] },
  { city: "Moga", state: "Punjab", district: "Moga", mandis: ["Moga Mandi", "Bagha Purana Mandi"] },
  { city: "Faridkot", state: "Punjab", district: "Faridkot", mandis: ["Faridkot Mandi"] },
  { city: "Muktsar", state: "Punjab", district: "Sri Muktsar Sahib", mandis: ["Muktsar Mandi", "Malout Mandi"] },
  { city: "Barnala", state: "Punjab", district: "Barnala", mandis: ["Barnala Mandi", "Tapa Mandi"] },
  { city: "Hoshiarpur", state: "Punjab", district: "Hoshiarpur", mandis: ["Hoshiarpur Mandi", "Dasuya Mandi"] },
  { city: "Kapurthala", state: "Punjab", district: "Kapurthala", mandis: ["Kapurthala Mandi", "Phagwara Mandi"] },
  { city: "Gurdaspur", state: "Punjab", district: "Gurdaspur", mandis: ["Gurdaspur Mandi", "Batala Mandi"] },
  { city: "Pathankot", state: "Punjab", district: "Pathankot", mandis: ["Pathankot Mandi"] },
  { city: "Tarn Taran", state: "Punjab", district: "Tarn Taran", mandis: ["Tarn Taran Mandi", "Patti Mandi"] },
  { city: "Mohali", state: "Punjab", district: "Sahibzada Ajit Singh Nagar", mandis: ["Mohali Mandi"] },
  { city: "Rupnagar", state: "Punjab", district: "Rupnagar", mandis: ["Rupnagar Mandi"] },

  // ---------- Haryana ----------
  { city: "Panipat", state: "Haryana", district: "Panipat", mandis: ["Panipat Mandi", "Samalkha Mandi", "Israna Mandi"] },
  { city: "Karnal", state: "Haryana", district: "Karnal", mandis: ["Karnal Mandi", "Nilokheri Mandi", "Gharaunda Mandi"] },
  { city: "Hisar", state: "Haryana", district: "Hisar", mandis: ["Hisar Mandi", "Barwala Mandi", "Hansi Mandi"] },
  { city: "Sirsa", state: "Haryana", district: "Sirsa", mandis: ["Sirsa Mandi", "Rania Mandi", "Ellenabad Mandi"] },
  { city: "Rohtak", state: "Haryana", district: "Rohtak", mandis: ["Rohtak Mandi", "Kalanaur Mandi"] },
  { city: "Jind", state: "Haryana", district: "Jind", mandis: ["Jind Mandi", "Safidon Mandi", "Narwana Mandi"] },
  { city: "Kaithal", state: "Haryana", district: "Kaithal", mandis: ["Kaithal Mandi", "Pundri Mandi"] },
  { city: "Kurukshetra", state: "Haryana", district: "Kurukshetra", mandis: ["Kurukshetra Mandi", "Shahabad Mandi", "Pehowa Mandi"] },
  { city: "Ambala", state: "Haryana", district: "Ambala", mandis: ["Ambala Mandi", "Naraingarh Mandi"] },
  { city: "Yamunanagar", state: "Haryana", district: "Yamunanagar", mandis: ["Yamunanagar Mandi", "Jagadhri Mandi"] },
  { city: "Sonipat", state: "Haryana", district: "Sonipat", mandis: ["Sonipat Mandi", "Ganaur Mandi", "Kharkhoda Mandi"] },
  { city: "Bhiwani", state: "Haryana", district: "Bhiwani", mandis: ["Bhiwani Mandi", "Bawani Khera Mandi"] },
  { city: "Charkhi Dadri", state: "Haryana", district: "Charkhi Dadri", mandis: ["Charkhi Dadri Mandi"] },
  { city: "Jhajjar", state: "Haryana", district: "Jhajjar", mandis: ["Jhajjar Mandi", "Bahadurgarh Mandi"] },
  { city: "Rewari", state: "Haryana", district: "Rewari", mandis: ["Rewari Mandi", "Bawal Mandi"] },
  { city: "Mahendragarh", state: "Haryana", district: "Mahendragarh", mandis: ["Narnaul Mandi"] },
  { city: "Palwal", state: "Haryana", district: "Palwal", mandis: ["Palwal Mandi", "Hodal Mandi"] },
  { city: "Fatehabad", state: "Haryana", district: "Fatehabad", mandis: ["Fatehabad Mandi", "Tohana Mandi"] },

  // ---------- Rajasthan ----------
  { city: "Jaipur", state: "Rajasthan", district: "Jaipur", mandis: ["Jaipur APMC", "Sanganer Mandi", "Chomu Mandi"] },
  { city: "Jodhpur", state: "Rajasthan", district: "Jodhpur", mandis: ["Jodhpur APMC", "Pipar City Mandi"] },
  { city: "Kota", state: "Rajasthan", district: "Kota", mandis: ["Kota Mandi", "Ramganj Mandi"] },
  { city: "Ajmer", state: "Rajasthan", district: "Ajmer", mandis: ["Ajmer Mandi", "Kishangarh Mandi"] },
  { city: "Udaipur", state: "Rajasthan", district: "Udaipur", mandis: ["Udaipur Mandi", "Rishabhdev Mandi"] },
  { city: "Alwar", state: "Rajasthan", district: "Alwar", mandis: ["Alwar Mandi", "Khairthal Mandi"] },
  { city: "Bharatpur", state: "Rajasthan", district: "Bharatpur", mandis: ["Bharatpur Mandi", "Deeg Mandi"] },
  { city: "Sri Ganganagar", state: "Rajasthan", district: "Sri Ganganagar", mandis: ["Sri Ganganagar Mandi", "Suratgarh Mandi"] },
  { city: "Hanumangarh", state: "Rajasthan", district: "Hanumangarh", mandis: ["Hanumangarh Mandi", "Nohar Mandi"] },
  { city: "Bikaner", state: "Rajasthan", district: "Bikaner", mandis: ["Bikaner Mandi", "Nokha Mandi"] },
  { city: "Sikar", state: "Rajasthan", district: "Sikar", mandis: ["Sikar Mandi", "Fatehpur Mandi"] },
  { city: "Jhunjhunu", state: "Rajasthan", district: "Jhunjhunu", mandis: ["Jhunjhunu Mandi", "Nawalgarh Mandi"] },
  { city: "Nagaur", state: "Rajasthan", district: "Nagaur", mandis: ["Nagaur Mandi", "Merta Mandi"] },
  { city: "Pali", state: "Rajasthan", district: "Pali", mandis: ["Pali Mandi", "Marwar Junction Mandi"] },
  { city: "Barmer", state: "Rajasthan", district: "Barmer", mandis: ["Barmer Mandi", "Balotra Mandi"] },
  { city: "Jalore", state: "Rajasthan", district: "Jalore", mandis: ["Jalore Mandi", "Bhinmal Mandi"] },
  { city: "Sirohi", state: "Rajasthan", district: "Sirohi", mandis: ["Abu Road Mandi"] },
  { city: "Bhilwara", state: "Rajasthan", district: "Bhilwara", mandis: ["Bhilwara Mandi", "Mandalgarh Mandi"] },
  { city: "Chittorgarh", state: "Rajasthan", district: "Chittorgarh", mandis: ["Chittorgarh Mandi", "Nimbahera Mandi"] },
  { city: "Banswara", state: "Rajasthan", district: "Banswara", mandis: ["Banswara Mandi"] },
  { city: "Dungarpur", state: "Rajasthan", district: "Dungarpur", mandis: ["Dungarpur Mandi"] },
  { city: "Tonk", state: "Rajasthan", district: "Tonk", mandis: ["Tonk Mandi", "Deoli Mandi"] },
  { city: "Sawai Madhopur", state: "Rajasthan", district: "Sawai Madhopur", mandis: ["Sawai Madhopur Mandi"] },
  { city: "Karauli", state: "Rajasthan", district: "Karauli", mandis: ["Karauli Mandi"] },
  { city: "Dholpur", state: "Rajasthan", district: "Dholpur", mandis: ["Dholpur Mandi"] },
  { city: "Baran", state: "Rajasthan", district: "Baran", mandis: ["Baran Mandi", "Shahabad Mandi"] },
  { city: "Jhalawar", state: "Rajasthan", district: "Jhalawar", mandis: ["Jhalawar Mandi", "Pirawa Mandi"] },

  // ---------- Maharashtra ----------
  { city: "Mumbai", state: "Maharashtra", district: "Navi Mumbai", mandis: ["Vashi APMC", "Kharghar Mandi"] },
  { city: "Pune", state: "Maharashtra", district: "Pune", mandis: ["Pune APMC", "Hadapsar Mandi"] },
  { city: "Nashik", state: "Maharashtra", district: "Nashik", mandis: ["Nashik APMC", "Pimpalgaon Mandi", "Lasalgaon Mandi"] },
  { city: "Nagpur", state: "Maharashtra", district: "Nagpur", mandis: ["Nagpur APMC", "Sitabuldi Mandi", "Kamptee Mandi"] },
  { city: "Aurangabad", state: "Maharashtra", district: "Aurangabad", mandis: ["Aurangabad APMC", "Paithan Mandi"] },
  { city: "Solapur", state: "Maharashtra", district: "Solapur", mandis: ["Solapur APMC", "Pandharpur Mandi"] },
  { city: "Kolhapur", state: "Maharashtra", district: "Kolhapur", mandis: ["Kolhapur APMC", "Ichalkaranji Mandi"] },
  { city: "Jalna", state: "Maharashtra", district: "Jalna", mandis: ["Jalna APMC", "Badnapur Mandi"] },
  { city: "Ahmednagar", state: "Maharashtra", district: "Ahmednagar", mandis: ["Ahmednagar APMC", "Shrirampur Mandi", "Rahuri Mandi"] },
  { city: "Sangli", state: "Maharashtra", district: "Sangli", mandis: ["Sangli APMC", "Miraj Mandi"] },
  { city: "Satara", state: "Maharashtra", district: "Satara", mandis: ["Satara APMC", "Karad Mandi"] },
  { city: "Latur", state: "Maharashtra", district: "Latur", mandis: ["Latur APMC", "Nilanga Mandi"] },
  { city: "Amravati", state: "Maharashtra", district: "Amravati", mandis: ["Amravati APMC", "Achalpur Mandi"] },
  { city: "Akola", state: "Maharashtra", district: "Akola", mandis: ["Akola APMC", "Akot Mandi"] },
  { city: "Yavatmal", state: "Maharashtra", district: "Yavatmal", mandis: ["Yavatmal APMC", "Pusad Mandi"] },
  { city: "Jalgaon", state: "Maharashtra", district: "Jalgaon", mandis: ["Jalgaon APMC", "Raver Mandi", "Chopda Mandi"] },
  { city: "Dhule", state: "Maharashtra", district: "Dhule", mandis: ["Dhule APMC", "Shirpur Mandi"] },
  { city: "Nanded", state: "Maharashtra", district: "Nanded", mandis: ["Nanded APMC", "Biloli Mandi"] },
  { city: "Parbhani", state: "Maharashtra", district: "Parbhani", mandis: ["Parbhani APMC"] },
  { city: "Beed", state: "Maharashtra", district: "Beed", mandis: ["Beed APMC", "Ambajogai Mandi"] },
  { city: "Osmanabad", state: "Maharashtra", district: "Dharashiv", mandis: ["Osmanabad APMC"] },
  { city: "Buldhana", state: "Maharashtra", district: "Buldhana", mandis: ["Buldhana APMC", "Khamgaon Mandi"] },
  { city: "Wardha", state: "Maharashtra", district: "Wardha", mandis: ["Wardha APMC", "Arvi Mandi"] },
  { city: "Chandrapur", state: "Maharashtra", district: "Chandrapur", mandis: ["Chandrapur APMC"] },
  { city: "Gondia", state: "Maharashtra", district: "Gondia", mandis: ["Gondia APMC", "Tirora Mandi"] },
  { city: "Ratnagiri", state: "Maharashtra", district: "Ratnagiri", mandis: ["Ratnagiri APMC"] },
  { city: "Nandurbar", state: "Maharashtra", district: "Nandurbar", mandis: ["Nandurbar APMC", "Shahada Mandi"] },

  // ---------- Gujarat ----------
  { city: "Ahmedabad", state: "Gujarat", district: "Ahmedabad", mandis: ["Ahmedabad APMC", "Naroda Mandi", "Daskroi Mandi"] },
  { city: "Surat", state: "Gujarat", district: "Surat", mandis: ["Surat APMC", "Bardoli Mandi"] },
  { city: "Rajkot", state: "Gujarat", district: "Rajkot", mandis: ["Rajkot APMC", "Gondal Mandi"] },
  { city: "Vadodara", state: "Gujarat", district: "Vadodara", mandis: ["Vadodara APMC", "Karjan Mandi"] },
  { city: "Anand", state: "Gujarat", district: "Anand", mandis: ["Anand APMC", "Kheda Mandi"] },
  { city: "Bhavnagar", state: "Gujarat", district: "Bhavnagar", mandis: ["Bhavnagar APMC", "Mahuva Mandi"] },
  { city: "Junagadh", state: "Gujarat", district: "Junagadh", mandis: ["Junagadh APMC", "Keshod Mandi"] },
  { city: "Jamnagar", state: "Gujarat", district: "Jamnagar", mandis: ["Jamnagar APMC", "Dhrol Mandi"] },
  { city: "Mehsana", state: "Gujarat", district: "Mehsana", mandis: ["Mehsana APMC", "Unjha Mandi"] },
  { city: "Banaskantha", state: "Gujarat", district: "Banaskantha", mandis: ["Palanpur Mandi", "Deesa Mandi"] },
  { city: "Sabarkantha", state: "Gujarat", district: "Sabarkantha", mandis: ["Himatnagar Mandi"] },
  { city: "Gandhinagar", state: "Gujarat", district: "Gandhinagar", mandis: ["Kalol Mandi"] },
  { city: "Kheda", state: "Gujarat", district: "Kheda", mandis: ["Nadiad Mandi"] },
  { city: "Panchmahal", state: "Gujarat", district: "Panchmahal", mandis: ["Godhra Mandi"] },
  { city: "Bharuch", state: "Gujarat", district: "Bharuch", mandis: ["Bharuch APMC", "Ankleshwar Mandi"] },
  { city: "Valsad", state: "Gujarat", district: "Valsad", mandis: ["Valsad APMC", "Vapi Mandi"] },
  { city: "Navsari", state: "Gujarat", district: "Navsari", mandis: ["Navsari APMC", "Jalalpore Mandi"] },
  { city: "Amreli", state: "Gujarat", district: "Amreli", mandis: ["Amreli APMC", "Rajula Mandi"] },
  { city: "Surendranagar", state: "Gujarat", district: "Surendranagar", mandis: ["Surendranagar Mandi", "Dhrangadhra Mandi"] },
  { city: "Kutch", state: "Gujarat", district: "Kachchh", mandis: ["Bhuj Mandi", "Anjar Mandi"] },

  // ---------- Madhya Pradesh ----------
  { city: "Bhopal", state: "Madhya Pradesh", district: "Bhopal", mandis: ["Bhopal APMC", "Berasia Mandi"] },
  { city: "Indore", state: "Madhya Pradesh", district: "Indore", mandis: ["Indore APMC", "Pithampur Mandi", "Depalpur Mandi"] },
  { city: "Jabalpur", state: "Madhya Pradesh", district: "Jabalpur", mandis: ["Jabalpur APMC", "Patan Mandi"] },
  { city: "Gwalior", state: "Madhya Pradesh", district: "Gwalior", mandis: ["Gwalior Mandi", "Dabra Mandi"] },
  { city: "Ujjain", state: "Madhya Pradesh", district: "Ujjain", mandis: ["Ujjain APMC", "Tarana Mandi"] },
  { city: "Dewas", state: "Madhya Pradesh", district: "Dewas", mandis: ["Dewas APMC", "Sonkatch Mandi"] },
  { city: "Sagar", state: "Madhya Pradesh", district: "Sagar", mandis: ["Sagar APMC", "Khurai Mandi"] },
  { city: "Rewa", state: "Madhya Pradesh", district: "Rewa", mandis: ["Rewa APMC", "Mauganj Mandi"] },
  { city: "Satna", state: "Madhya Pradesh", district: "Satna", mandis: ["Satna APMC", "Amarpatan Mandi"] },
  { city: "Khandwa", state: "Madhya Pradesh", district: "Khandwa", mandis: ["Khandwa APMC", "Pandhurna Mandi"] },
  { city: "Burhanpur", state: "Madhya Pradesh", district: "Burhanpur", mandis: ["Burhanpur APMC"] },
  { city: "Hoshangabad", state: "Madhya Pradesh", district: "Narmadapuram", mandis: ["Hoshangabad Mandi", "Harda Mandi"] },
  { city: "Vidisha", state: "Madhya Pradesh", district: "Vidisha", mandis: ["Vidisha Mandi", "Basoda Mandi"] },
  { city: "Chhindwara", state: "Madhya Pradesh", district: "Chhindwara", mandis: ["Chhindwara APMC", "Pandhurna Mandi"] },
  { city: "Sehore", state: "Madhya Pradesh", district: "Sehore", mandis: ["Sehore Mandi", "Ashta Mandi"] },
  { city: "Shajapur", state: "Madhya Pradesh", district: "Shajapur", mandis: ["Shajapur Mandi", "Susner Mandi"] },
  { city: "Rajgarh", state: "Madhya Pradesh", district: "Rajgarh", mandis: ["Biaora Mandi", "Khilchipur Mandi"] },
  { city: "Katni", state: "Madhya Pradesh", district: "Katni", mandis: ["Katni Mandi"] },
  { city: "Damoh", state: "Madhya Pradesh", district: "Damoh", mandis: ["Damoh Mandi"] },
  { city: "Tikamgarh", state: "Madhya Pradesh", district: "Tikamgarh", mandis: ["Tikamgarh Mandi"] },

  // ---------- Bihar ----------
  { city: "Patna", state: "Bihar", district: "Patna", mandis: ["Patna APMC", "Bailey Road Mandi", "Danapur Mandi"] },
  { city: "Gaya", state: "Bihar", district: "Gaya", mandis: ["Gaya Mandi", "Bodh Gaya Mandi"] },
  { city: "Muzaffarpur", state: "Bihar", district: "Muzaffarpur", mandis: ["Muzaffarpur Mandi", "Motipur Mandi"] },
  { city: "Bhagalpur", state: "Bihar", district: "Bhagalpur", mandis: ["Bhagalpur Mandi", "Naugachhia Mandi"] },
  { city: "Darbhanga", state: "Bihar", district: "Darbhanga", mandis: ["Darbhanga Mandi", "Benipur Mandi"] },
  { city: "Purnia", state: "Bihar", district: "Purnia", mandis: ["Purnia Mandi", "Kasba Mandi"] },
  { city: "Samastipur", state: "Bihar", district: "Samastipur", mandis: ["Samastipur Mandi", "Rosera Mandi"] },
  { city: "Begusarai", state: "Bihar", district: "Begusarai", mandis: ["Begusarai Mandi"] },
  { city: "Nalanda", state: "Bihar", district: "Nalanda", mandis: ["Bihar Sharif Mandi", "Rajgir Mandi"] },
  { city: "Saran", state: "Bihar", district: "Saran", mandis: ["Chhapra Mandi"] },
  { city: "Siwan", state: "Bihar", district: "Siwan", mandis: ["Siwan Mandi", "Maharajganj Mandi"] },
  { city: "Gopalganj", state: "Bihar", district: "Gopalganj", mandis: ["Gopalganj Mandi"] },
  { city: "East Champaran", state: "Bihar", district: "Purbi Champaran", mandis: ["Motihari Mandi"] },
  { city: "West Champaran", state: "Bihar", district: "Paschim Champaran", mandis: ["Bettiah Mandi"] },
  { city: "Saharsa", state: "Bihar", district: "Saharsa", mandis: ["Saharsa Mandi"] },
  { city: "Katihar", state: "Bihar", district: "Katihar", mandis: ["Katihar Mandi"] },
  { city: "Araria", state: "Bihar", district: "Araria", mandis: ["Araria Mandi"] },
  { city: "Bhojpur", state: "Bihar", district: "Bhojpur", mandis: ["Arrah Mandi"] },
  { city: "Rohtas", state: "Bihar", district: "Rohtas", mandis: ["Sasaram Mandi"] },
  { city: "Nawada", state: "Bihar", district: "Nawada", mandis: ["Nawada Mandi"] },

  // ---------- Jharkhand ----------
  { city: "Ranchi", state: "Jharkhand", district: "Ranchi", mandis: ["Ranchi APMC", "Bundy Mandi"] },
  { city: "Jamshedpur", state: "Jharkhand", district: "East Singhbhum", mandis: ["Jamshedpur Mandi", "Ghatshila Mandi"] },
  { city: "Dhanbad", state: "Jharkhand", district: "Dhanbad", mandis: ["Dhanbad Mandi"] },
  { city: "Bokaro", state: "Jharkhand", district: "Bokaro", mandis: ["Bokaro Mandi", "Chas Mandi"] },
  { city: "Hazaribagh", state: "Jharkhand", district: "Hazaribagh", mandis: ["Hazaribagh Mandi"] },
  { city: "Deoghar", state: "Jharkhand", district: "Deoghar", mandis: ["Deoghar Mandi"] },
  { city: "Dumka", state: "Jharkhand", district: "Dumka", mandis: ["Dumka Mandi"] },
  { city: "Palamu", state: "Jharkhand", district: "Palamu", mandis: ["Medininagar Mandi"] },
  { city: "Gumla", state: "Jharkhand", district: "Gumla", mandis: ["Gumla Mandi"] },
  { city: "Ramgarh", state: "Jharkhand", district: "Ramgarh", mandis: ["Ramgarh Mandi"] },

  // ---------- West Bengal ----------
  { city: "Kolkata", state: "West Bengal", district: "Kolkata", mandis: ["Sealdah Mandi", "Howrah Mandi"] },
  { city: "Siliguri", state: "West Bengal", district: "Darjeeling", mandis: ["Siliguri APMC", "Matigara Mandi"] },
  { city: "Burdwan", state: "West Bengal", district: "Bardhaman", mandis: ["Burdwan Mandi", "Guskara Mandi"] },
  { city: "Krishnanagar", state: "West Bengal", district: "Nadia", mandis: ["Krishnanagar Mandi", "Ranaghat Mandi"] },
  { city: "Malda", state: "West Bengal", district: "Malda", mandis: ["Malda Mandi", "English Bazar Mandi"] },
  { city: "Murshidabad", state: "West Bengal", district: "Murshidabad", mandis: ["Berhampore Mandi", "Kandi Mandi"] },
  { city: "Durgapur", state: "West Bengal", district: "Paschim Bardhaman", mandis: ["Durgapur Mandi", "Asansol Mandi"] },
  { city: "Raiganj", state: "West Bengal", district: "Uttar Dinajpur", mandis: ["Raiganj Mandi"] },
  { city: "Balurghat", state: "West Bengal", district: "Dakshin Dinajpur", mandis: ["Balurghat Mandi"] },
  { city: "Cooch Behar", state: "West Bengal", district: "Cooch Behar", mandis: ["Cooch Behar Mandi"] },
  { city: "Barasat", state: "West Bengal", district: "North 24 Parganas", mandis: ["Barasat Mandi", "Barrackpore Mandi"] },
  { city: "Diamond Harbour", state: "West Bengal", district: "South 24 Parganas", mandis: ["Diamond Harbour Mandi"] },
  { city: "Hooghly", state: "West Bengal", district: "Hooghly", mandis: ["Chinsurah Mandi", "Serampore Mandi"] },

  // ---------- Odisha ----------
  { city: "Bhubaneswar", state: "Odisha", district: "Khordha", mandis: ["Bhubaneswar APMC", "Jatni Mandi"] },
  { city: "Cuttack", state: "Odisha", district: "Cuttack", mandis: ["Cuttack APMC", "Mandapada Mandi", "Choudwar Mandi"] },
  { city: "Sambalpur", state: "Odisha", district: "Sambalpur", mandis: ["Sambalpur APMC", "Burla Mandi"] },
  { city: "Berhampur", state: "Odisha", district: "Ganjam", mandis: ["Berhampur Mandi", "Chatrapur Mandi"] },
  { city: "Rourkela", state: "Odisha", district: "Sundargarh", mandis: ["Rourkela Mandi"] },
  { city: "Balasore", state: "Odisha", district: "Balasore", mandis: ["Balasore Mandi", "Jaleswar Mandi"] },
  { city: "Baripada", state: "Odisha", district: "Mayurbhanj", mandis: ["Baripada Mandi", "Udala Mandi"] },
  { city: "Jharsuguda", state: "Odisha", district: "Jharsuguda", mandis: ["Jharsuguda Mandi"] },
  { city: "Angul", state: "Odisha", district: "Angul", mandis: ["Angul Mandi", "Talcher Mandi"] },
  { city: "Dhenkanal", state: "Odisha", district: "Dhenkanal", mandis: ["Dhenkanal Mandi"] },
  { city: "Puri", state: "Odisha", district: "Puri", mandis: ["Puri Mandi", "Nimapada Mandi"] },
  { city: "Kendujhar", state: "Odisha", district: "Kendujhar", mandis: ["Kendujhar Mandi", "Anandapur Mandi"] },
  { city: "Bhawanipatna", state: "Odisha", district: "Kalahandi", mandis: ["Bhawanipatna Mandi"] },
  { city: "Koraput", state: "Odisha", district: "Koraput", mandis: ["Koraput Mandi", "Jeypore Mandi"] },
  { city: "Rayagada", state: "Odisha", district: "Rayagada", mandis: ["Rayagada Mandi"] },
  { city: "Paradip", state: "Odisha", district: "Jagatsinghpur", mandis: ["Paradip Mandi"] },
  { city: "Boudh", state: "Odisha", district: "Boudh", mandis: ["Boudh Mandi"] },
  { city: "Phulbani", state: "Odisha", district: "Kandhamal", mandis: ["Phulbani Mandi"] },

  // ---------- Telangana ----------
  { city: "Hyderabad", state: "Telangana", district: "Hyderabad", mandis: ["Malkajgiri APMC", "Malakpet Mandi", "Bowenpally Mandi"] },
  { city: "Warangal", state: "Telangana", district: "Warangal", mandis: ["Warangal APMC", "Jangaon Mandi"] },
  { city: "Nizamabad", state: "Telangana", district: "Nizamabad", mandis: ["Nizamabad APMC", "Bodhan Mandi"] },
  { city: "Karimnagar", state: "Telangana", district: "Karimnagar", mandis: ["Karimnagar APMC", "Jagtial Mandi"] },
  { city: "Khammam", state: "Telangana", district: "Khammam", mandis: ["Khammam APMC", "Kothagudem Mandi"] },
  { city: "Nalgonda", state: "Telangana", district: "Nalgonda", mandis: ["Nalgonda APMC", "Miryalaguda Mandi"] },
  { city: "Mahbubnagar", state: "Telangana", district: "Mahbubnagar", mandis: ["Mahbubnagar APMC", "Jadcherla Mandi"] },
  { city: "Siddipet", state: "Telangana", district: "Siddipet", mandis: ["Siddipet APMC"] },
  { city: "Suryapet", state: "Telangana", district: "Suryapet", mandis: ["Suryapet APMC"] },
  { city: "Adilabad", state: "Telangana", district: "Adilabad", mandis: ["Adilabad APMC"] },
  { city: "Medak", state: "Telangana", district: "Medak", mandis: ["Sangareddy Mandi"] },
  { city: "Kamareddy", state: "Telangana", district: "Kamareddy", mandis: ["Kamareddy APMC"] },

  // ---------- Andhra Pradesh ----------
  { city: "Vijayawada", state: "Andhra Pradesh", district: "Krishna", mandis: ["Vijayawada APMC", "Nandigama Mandi"] },
  { city: "Visakhapatnam", state: "Andhra Pradesh", district: "Visakhapatnam", mandis: ["Vizag Mandi", "Anakapalle Mandi"] },
  { city: "Guntur", state: "Andhra Pradesh", district: "Guntur", mandis: ["Guntur APMC", "Ponnur Mandi", "Tenali Mandi"] },
  { city: "Tirupati", state: "Andhra Pradesh", district: "Chittoor", mandis: ["Tirupati Mandi", "Chittoor Mandi"] },
  { city: "Kurnool", state: "Andhra Pradesh", district: "Kurnool", mandis: ["Kurnool APMC", "Nandyal Mandi"] },
  { city: "Rajahmundry", state: "Andhra Pradesh", district: "East Godavari", mandis: ["Rajahmundry APMC", "Kakinada Mandi"] },
  { city: "Eluru", state: "Andhra Pradesh", district: "Eluru", mandis: ["Eluru APMC", "Bhimavaram Mandi"] },
  { city: "Anantapur", state: "Andhra Pradesh", district: "Anantapur", mandis: ["Anantapur APMC", "Dharmavaram Mandi"] },
  { city: "Kadapa", state: "Andhra Pradesh", district: "YSR Kadapa", mandis: ["Kadapa APMC", "Proddatur Mandi"] },
  { city: "Ongole", state: "Andhra Pradesh", district: "Prakasam", mandis: ["Ongole APMC", "Markapur Mandi"] },
  { city: "Srikakulam", state: "Andhra Pradesh", district: "Srikakulam", mandis: ["Srikakulam APMC"] },
  { city: "Vizianagaram", state: "Andhra Pradesh", district: "Vizianagaram", mandis: ["Vizianagaram APMC"] },
  { city: "Amaravati", state: "Andhra Pradesh", district: "Guntur", mandis: ["Mangalagiri Mandi"] },

  // ---------- Karnataka ----------
  { city: "Bengaluru", state: "Karnataka", district: "Bengaluru", mandis: ["BMIC Market", "Yeshwanthpur APMC", "Dasanapura APMC"] },
  { city: "Mysuru", state: "Karnataka", district: "Mysuru", mandis: ["Mysuru APMC", "Nanjangud Mandi"] },
  { city: "Davangere", state: "Karnataka", district: "Davangere", mandis: ["Davangere APMC", "Harihar Mandi"] },
  { city: "Hubli", state: "Karnataka", district: "Dharwad", mandis: ["Hubli APMC", "Amargol APMC"] },
  { city: "Belgaum", state: "Karnataka", district: "Belagavi", mandis: ["Belgaum APMC", "Gokak Mandi"] },
  { city: "Mangalore", state: "Karnataka", district: "Dakshina Kannada", mandis: ["Mangalore APMC", "Puttur Mandi"] },
  { city: "Ballari", state: "Karnataka", district: "Ballari", mandis: ["Ballari APMC", "Hospet Mandi"] },
  { city: "Kalaburagi", state: "Karnataka", district: "Kalaburagi", mandis: ["Gulbarga APMC", "Sedam Mandi"] },
  { city: "Bijapur", state: "Karnataka", district: "Vijayapura", mandis: ["Bijapur APMC", "Basavana Bagewadi Mandi"] },
  { city: "Shimoga", state: "Karnataka", district: "Shivamogga", mandis: ["Shimoga APMC", "Bhadravati Mandi"] },
  { city: "Tumakuru", state: "Karnataka", district: "Tumakuru", mandis: ["Tumkur APMC", "Sira Mandi"] },
  { city: "Raichur", state: "Karnataka", district: "Raichur", mandis: ["Raichur APMC", "Sindhanur Mandi"] },
  { city: "Bagalkot", state: "Karnataka", district: "Bagalkot", mandis: ["Bagalkot APMC", "Jamkhandi Mandi"] },
  { city: "Hassan", state: "Karnataka", district: "Hassan", mandis: ["Hassan APMC", "Arsikere Mandi"] },
  { city: "Chitradurga", state: "Karnataka", district: "Chitradurga", mandis: ["Chitradurga APMC"] },
  { city: "Kolar", state: "Karnataka", district: "Kolar", mandis: ["Kolar APMC", "KGF Mandi"] },
  { city: "Mandya", state: "Karnataka", district: "Mandya", mandis: ["Mandya APMC", "Maddur Mandi"] },
  { city: "Udupi", state: "Karnataka", district: "Udupi", mandis: ["Udupi APMC"] },
  { city: "Karwar", state: "Karnataka", district: "Uttara Kannada", mandis: ["Karwar Mandi"] },
  { city: "Bidar", state: "Karnataka", district: "Bidar", mandis: ["Bidar APMC"] },

  // ---------- Tamil Nadu ----------
  { city: "Chennai", state: "Tamil Nadu", district: "Chennai", mandis: ["Koyambedu Market", "Tondiarpet Mandi"] },
  { city: "Coimbatore", state: "Tamil Nadu", district: "Coimbatore", mandis: ["Coimbatore APMC", "Pollachi Mandi"] },
  { city: "Madurai", state: "Tamil Nadu", district: "Madurai", mandis: ["Madurai APMC", "Melur Mandi"] },
  { city: "Salem", state: "Tamil Nadu", district: "Salem", mandis: ["Salem APMC", "Mettur Mandi"] },
  { city: "Tiruchirappalli", state: "Tamil Nadu", district: "Tiruchirappalli", mandis: ["Trichy APMC", "Musiri Mandi"] },
  { city: "Erode", state: "Tamil Nadu", district: "Erode", mandis: ["Erode APMC", "Gobichettipalayam Mandi", "Turmeric Market"] },
  { city: "Thanjavur", state: "Tamil Nadu", district: "Thanjavur", mandis: ["Thanjavur APMC", "Kumbakonam Mandi"] },
  { city: "Tirunelveli", state: "Tamil Nadu", district: "Tirunelveli", mandis: ["Tirunelveli APMC"] },
  { city: "Vellore", state: "Tamil Nadu", district: "Vellore", mandis: ["Vellore APMC", "Ranipet Mandi"] },
  { city: "Villupuram", state: "Tamil Nadu", district: "Villupuram", mandis: ["Villupuram APMC"] },
  { city: "Thoothukudi", state: "Tamil Nadu", district: "Thoothukudi", mandis: ["Tuticorin APMC"] },
  { city: "Dindigul", state: "Tamil Nadu", district: "Dindigul", mandis: ["Dindigul APMC", "Oddanchatram Mandi"] },
  { city: "Karur", state: "Tamil Nadu", district: "Karur", mandis: ["Karur APMC"] },
  { city: "Namakkal", state: "Tamil Nadu", district: "Namakkal", mandis: ["Namakkal APMC", "Tiruchengode Mandi"] },
  { city: "Hosur", state: "Tamil Nadu", district: "Krishnagiri", mandis: ["Hosur APMC", "Krishnagiri Mandi"] },

  // ---------- Kerala ----------
  { city: "Kochi", state: "Kerala", district: "Ernakulam", mandis: ["Kochi APMC", "Aluva Mandi"] },
  { city: "Thiruvananthapuram", state: "Kerala", district: "Thiruvananthapuram", mandis: ["Trivandrum Mandi", "Neyyattinkara Mandi"] },
  { city: "Thrissur", state: "Kerala", district: "Thrissur", mandis: ["Thrissur APMC", "Kodungallur Mandi"] },
  { city: "Kozhikode", state: "Kerala", district: "Kozhikode", mandis: ["Kozhikode APMC", "Feroke Mandi"] },
  { city: "Palakkad", state: "Kerala", district: "Palakkad", mandis: ["Palakkad APMC"] },
  { city: "Kollam", state: "Kerala", district: "Kollam", mandis: ["Kollam APMC"] },
  { city: "Kottayam", state: "Kerala", district: "Kottayam", mandis: ["Kottayam APMC"] },
  { city: "Alappuzha", state: "Kerala", district: "Alappuzha", mandis: ["Alappuzha APMC"] },
  { city: "Kannur", state: "Kerala", district: "Kannur", mandis: ["Kannur APMC"] },

  // ---------- Assam & Northeast ----------
  { city: "Guwahati", state: "Assam", district: "Kamrup", mandis: ["Fancy Bazar Mandi", "Paltan Bazar Mandi"] },
  { city: "Silchar", state: "Assam", district: "Cachar", mandis: ["Silchar Mandi"] },
  { city: "Dibrugarh", state: "Assam", district: "Dibrugarh", mandis: ["Dibrugarh Mandi"] },
  { city: "Jorhat", state: "Assam", district: "Jorhat", mandis: ["Jorhat Mandi"] },
  { city: "Nagaon", state: "Assam", district: "Nagaon", mandis: ["Nagaon Mandi"] },
  { city: "Tezpur", state: "Assam", district: "Sonitpur", mandis: ["Tezpur Mandi"] },
  { city: "Shillong", state: "Meghalaya", district: "East Khasi Hills", mandis: ["Shillong Mandi"] },
  { city: "Agartala", state: "Tripura", district: "West Tripura", mandis: ["Agartala Mandi"] },
  { city: "Aizawl", state: "Mizoram", district: "Aizawl", mandis: ["Aizawl Mandi"] },
  { city: "Imphal", state: "Manipur", district: "Imphal West", mandis: ["Imphal Mandi"] },
  { city: "Kohima", state: "Nagaland", district: "Kohima", mandis: ["Kohima Mandi"] },
  { city: "Itanagar", state: "Arunachal Pradesh", district: "Papum Pare", mandis: ["Naharlagun Mandi"] },

  // ---------- Himachal, J&K, Hill states ----------
  { city: "Shimla", state: "Himachal Pradesh", district: "Shimla", mandis: ["Shimla Mandi"] },
  { city: "Solan", state: "Himachal Pradesh", district: "Solan", mandis: ["Solan Mandi"] },
  { city: "Mandi", state: "Himachal Pradesh", district: "Mandi", mandis: ["Mandi Mandi"] },
  { city: "Kangra", state: "Himachal Pradesh", district: "Kangra", mandis: ["Dharamshala Mandi", "Nurpur Mandi"] },
  { city: "Una", state: "Himachal Pradesh", district: "Una", mandis: ["Una Mandi"] },
  { city: "Srinagar", state: "Jammu & Kashmir", district: "Srinagar", mandis: ["Srinagar Mandi", "Parimpora Mandi"] },
  { city: "Jammu", state: "Jammu & Kashmir", district: "Jammu", mandis: ["Jammu Narwal Mandi"] },
  { city: "Kathua", state: "Jammu & Kashmir", district: "Kathua", mandis: ["Kathua Mandi"] },
  { city: "Pulwama", state: "Jammu & Kashmir", district: "Pulwama", mandis: ["Pulwama Mandi"] },
  { city: "Leh", state: "Ladakh", district: "Leh", mandis: ["Leh Mandi"] },

  // ---------- Others ----------
  { city: "Raipur", state: "Chhattisgarh", district: "Raipur", mandis: ["Raipur APMC", "Arang Mandi"] },
  { city: "Bilaspur", state: "Chhattisgarh", district: "Bilaspur", mandis: ["Bilaspur Mandi"] },
  { city: "Durg", state: "Chhattisgarh", district: "Durg", mandis: ["Durg Mandi", "Bhilai Mandi"] },
  { city: "Rajnandgaon", state: "Chhattisgarh", district: "Rajnandgaon", mandis: ["Rajnandgaon Mandi"] },
  { city: "Jagdalpur", state: "Chhattisgarh", district: "Bastar", mandis: ["Jagdalpur Mandi"] },
  { city: "Ambikapur", state: "Chhattisgarh", district: "Surguja", mandis: ["Ambikapur Mandi"] },
  { city: "Panaji", state: "Goa", district: "North Goa", mandis: ["Mapusa Mandi"] },
  { city: "Margao", state: "Goa", district: "South Goa", mandis: ["Margao Mandi"] },
  { city: "Puducherry", state: "Puducherry", district: "Puducherry", mandis: ["Puducherry APMC"] },
  { city: "Port Blair", state: "Andaman & Nicobar", district: "Port Blair", mandis: ["Port Blair Mandi"] },
];

/** Look up all location entries whose city / district / state / mandi names contain the query. */
export function searchMandiLocations(query: string): MandiLocation[] {
  const q = query.trim().toLowerCase();
  if (!q) return MANDI_LOCATIONS;
  return MANDI_LOCATIONS.filter(
    (loc) =>
      loc.city.toLowerCase().includes(q) ||
      loc.district.toLowerCase().includes(q) ||
      loc.state.toLowerCase().includes(q) ||
      loc.mandis.some((m) => m.toLowerCase().includes(q))
  );
}
