import { useState } from "react";
import { FileDown, Printer, ShieldCheck, ChevronDown, ChevronUp } from "lucide-react";
import type { TwinState } from "../../lib/digitalTwinData";

// ============================================================
// Phase 3 — Digital Twin → PMFBY Evidence Bridge
// Formats the twin's OWN yield-loss/damage estimate into a printable
// / downloadable evidence summary the farmer can show to their bank,
// CSC or insurance agent. It is NOT a government submission — no
// PMFBY/government API is called (none is publicly available).
// Every number is traced to where the twin computed it; nothing new
// is invented here.
// ============================================================

interface EvidenceSummary {
  generatedAt: string;
  location: string;
  coordinates: string;
  cropContext: string;
  fieldArea: string | null;
  damagePct: number; // 0-45, derived from the twin's yieldPct shortfall
  damageLabel: string;
  severity: "low" | "moderate" | "high";
  dateRange: string;
  drivers: string[];
  method: string;
}

/** Derive the evidence summary strictly from the twin's existing outputs. */
export function buildPmfbyEvidence(t: TwinState): EvidenceSummary {
  // The twin already computes a yield outlook advisory. Reuse its logic:
  // shortfall vs 100% potential == estimated damage.
  const yieldAdv = t.advisories.find((a) => a.type === "yield");
  const yieldPctMatch = yieldAdv?.title.match(/(\d+)% of potential/);
  const yieldPct = yieldPctMatch ? Number(yieldPctMatch[1]) : 100;
  const damagePct = Math.max(0, Math.min(45, 100 - yieldPct));

  // Damage drivers — only the ones the twin itself flagged.
  const drivers: string[] = [];
  const weekAvgMoisture =
    t.projection.length > 0
      ? t.projection.reduce((a, p) => a + p.moisture, 0) / t.projection.length
      : t.moisture1to3 * 100;
  const wiltingApprox = 14; // FAO-56 loam-band wilting point used by the twin's own model
  if (weekAvgMoisture < wiltingApprox + 4) drivers.push("projected root-zone moisture stress");
  if (t.airTemp > 38) drivers.push(`heat peaks of ${Math.round(t.airTemp)}°C`);
  const weekRain = t.projection.reduce((a, p) => a + p.rainMm, 0);
  if (weekRain > 150) drivers.push(`waterlogging risk (${Math.round(weekRain)} mm forecast rain / week)`);
  if (drivers.length === 0) drivers.push("no adverse drivers flagged in the current 7-day window");

  const severity: EvidenceSummary["severity"] = damagePct >= 20 ? "high" : damagePct >= 10 ? "moderate" : "low";
  const damageLabel =
    damagePct === 0
      ? "No estimated damage in the current 7-day window"
      : `Estimated ${damagePct}% yield shortfall vs. potential`;

  return {
    generatedAt: new Date().toLocaleString("en-IN"),
    location: [t.district, t.state].filter(Boolean).join(", ") || "Unknown",
    coordinates: `${t.lat.toFixed(4)}°N, ${t.lon.toFixed(4)}°E`,
    cropContext:
      t.crops && t.crops.length > 0
        ? `Top suited: ${t.crops
            .slice()
            .sort((a, b) => b.score - a.score)
            .slice(0, 3)
            .map((c) => c.name)
            .join(", ")}`
        : "Not assessed",
    fieldArea: t.areaAcres != null ? `${t.areaAcres} acres` : null,
    damagePct,
    damageLabel,
    severity,
    dateRange: `7-day projection window ending ${new Date(Date.now() + 7 * 86400000).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}`,
    drivers,
    method:
      "FAO-56 water-balance on Open-Meteo land-surface model (ECMWF/GFS soil analysis) at plot coordinates; FAO-56 (−1500 kPa) wilting thresholds by soil class. Model estimate — not a field survey or lab test.",
  };
}

const SEV_STYLE: Record<EvidenceSummary["severity"], string> = {
  low: "bg-emerald-50 text-emerald-700 border-emerald-200",
  moderate: "bg-amber-50 text-amber-700 border-amber-200",
  high: "bg-rose-50 text-rose-700 border-rose-200",
};

export default function PmfbyEvidenceExport({ twin }: { twin: TwinState }) {
  const [open, setOpen] = useState(false);
  const ev = buildPmfbyEvidence(twin);

  const doPrint = () => window.print();

  const doDownload = () => {
    const lines = [
      "PMFBY SUPPORTING EVIDENCE — generated by AgriNexus (KrishiMitra) Digital Twin",
      "================================================================",
      `Generated:            ${ev.generatedAt}`,
      `Location:             ${ev.location}`,
      `Coordinates:          ${ev.coordinates}`,
      ...(ev.fieldArea ? [`Field area:           ${ev.fieldArea}`] : []),
      `Crop context:         ${ev.cropContext}`,
      `Assessment window:    ${ev.dateRange}`,
      `Estimated damage:     ${ev.damagePct}% — ${ev.damageLabel}`,
      `Drivers flagged:      ${ev.drivers.join("; ")}`,
      "",
      "METHOD",
      ev.method,
      "",
      "HOW TO USE",
      "1. Print or show this card to your bank / CSC / insurance agent when filing",
      "   an intimation under PMFBY.",
      "2. This is a model estimate to SUPPORT your claim, not an official",
      "   assessment. The final loss assessment is done by the government's",
      "   own process (yield data + remote sensing).",
      "",
      "This document was produced by a private app. It is not issued by any",
      "government body and does not guarantee claim acceptance.",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `pmfby-evidence-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-3xl border border-slate-200/80 shadow-sm print:border-0 print:shadow-none">
      {/* Collapsed header row — lives inside the twin page sections */}
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-6 py-4 cursor-pointer print:hidden"
      >
        <span className="flex items-center gap-2 text-sm font-bold text-slate-900">
          <ShieldCheck className="w-4.5 h-4.5 text-indigo-600 w-5 h-5" />
          Export as PMFBY evidence
        </span>
        {open ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
      </button>

      {open && (
        <div className="px-6 pb-6 space-y-4">
          <div className="rounded-2xl border-2 border-dashed border-indigo-200 bg-indigo-50/40 p-5 space-y-3">
            <div className="flex items-start justify-between gap-3">
              <div>
                <p className="text-[10px] font-extrabold uppercase tracking-widest text-indigo-400">
                  PMFBY supporting evidence (model estimate)
                </p>
                <p className="text-[11px] text-slate-500 mt-0.5">Generated {ev.generatedAt}</p>
              </div>
              <span className={`shrink-0 px-2.5 py-1 rounded-full text-[10px] font-extrabold border ${SEV_STYLE[ev.severity]}`}>
                {ev.damagePct}% est. shortfall
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-2 text-xs">
              <p><span className="text-slate-400 font-semibold">Location:</span> <b className="text-slate-800">{ev.location}</b></p>
              <p><span className="text-slate-400 font-semibold">Coordinates:</span> <b className="text-slate-800">{ev.coordinates}</b></p>
              {ev.fieldArea && (
                <p><span className="text-slate-400 font-semibold">Field area:</span> <b className="text-slate-800">{ev.fieldArea}</b></p>
              )}
              <p><span className="text-slate-400 font-semibold">Crop context:</span> <b className="text-slate-800">{ev.cropContext}</b></p>
              <p className="sm:col-span-2"><span className="text-slate-400 font-semibold">Assessment window:</span> <b className="text-slate-800">{ev.dateRange}</b></p>
            </div>

            <p className="text-xs text-slate-700 leading-relaxed bg-white/70 rounded-xl p-3 border border-indigo-100">
              <b>{ev.damageLabel}.</b> Drivers flagged by the twin: {ev.drivers.join("; ")}.
            </p>

            <p className="text-[10px] text-slate-500 leading-relaxed">
              <b>Method:</b> {ev.method}
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2 print:hidden">
            <button
              onClick={doDownload}
              className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-bold hover:bg-indigo-700 transition-colors cursor-pointer"
            >
              <FileDown className="w-4 h-4" /> Download as text file
            </button>
            <button
              onClick={doPrint}
              className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl border border-slate-300 text-slate-700 text-xs font-bold hover:bg-slate-50 transition-colors cursor-pointer"
            >
              <Printer className="w-4 h-4" /> Print this card
            </button>
            <span className="text-[10px] text-slate-400 max-w-[240px] leading-snug">
              Show this to your bank / CSC / agent when intimating a crop loss. It supports — does not replace — the official assessment.
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
