// Auto-generated by scripts/prepare-kb.mjs from datasets/standardized_crops.csv.
// Mean growing conditions per crop — used by the crop recommender.
export interface CropCentroid {
  crop: string;
  count: number;
  n: number;
  p: number;
  k: number;
  temperature: number;
  humidity: number;
  ph: number;
  rainfall: number;
}

export const CROP_CENTROIDS: CropCentroid[] = [
  { crop: "Apple", count: 100, n: 20.8, p: 134.22, k: 199.89, temperature: 22.63, humidity: 92.33, ph: 5.93, rainfall: 112.65 },
  { crop: "Banana", count: 100, n: 100.23, p: 82.01, k: 50.05, temperature: 27.38, humidity: 80.36, ph: 5.98, rainfall: 104.63 },
  { crop: "Barley (Jau)", count: 192, n: 70, p: 40, k: 45, temperature: 20.37, humidity: 83.68, ph: 5.49, rainfall: 172.57 },
  { crop: "Bitter Gourd (Karela)", count: 9, n: 60, p: 10, k: 20, temperature: 27.19, humidity: 93.19, ph: 6.51, rainfall: 1684.13 },
  { crop: "Black Gram (Urad)", count: 100, n: 40.02, p: 67.47, k: 19.24, temperature: 29.97, humidity: 65.12, ph: 7.13, rainfall: 67.88 },
  { crop: "Black Pepper (Kali Mirch)", count: 71, n: 100, p: 60, k: 50, temperature: 25.04, humidity: 80.75, ph: 5, rainfall: 1829.25 },
  { crop: "Bottle Gourd (Lauki)", count: 11, n: 100, p: 50, k: 50, temperature: 27.94, humidity: 83.04, ph: 6.47, rainfall: 1006.88 },
  { crop: "Brinjal (Eggplant/Baingan)", count: 43, n: 80, p: 15, k: 40, temperature: 27.5, humidity: 80.75, ph: 6.52, rainfall: 1266.25 },
  { crop: "Cabbage (Band Gobi)", count: 21, n: 100, p: 65, k: 70, temperature: 28.1, humidity: 82.59, ph: 6.48, rainfall: 1078.53 },
  { crop: "Cardamom (Elaichi)", count: 41, n: 75, p: 75, k: 150, temperature: 26.12, humidity: 83, ph: 5.01, rainfall: 1707.45 },
  { crop: "Cauliflower (Phool Gobi)", count: 18, n: 80, p: 70, k: 50, temperature: 27.93, humidity: 82.92, ph: 6.49, rainfall: 1088.3 },
  { crop: "Chickpea (Gram)", count: 100, n: 40.09, p: 67.79, k: 79.92, temperature: 18.87, humidity: 16.86, ph: 7.34, rainfall: 80.06 },
  { crop: "Coconut (Nariyal)", count: 100, n: 21.98, p: 16.93, k: 30.59, temperature: 27.41, humidity: 94.84, ph: 5.98, rainfall: 175.69 },
  { crop: "Coffee", count: 100, n: 101.2, p: 28.74, k: 29.94, temperature: 25.54, humidity: 58.87, ph: 6.79, rainfall: 158.07 },
  { crop: "Coriander (Dhania)", count: 190, n: 10, p: 20, k: 20, temperature: 26.42, humidity: 85.21, ph: 6.5, rainfall: 937.34 },
  { crop: "Cotton (Kapash)", count: 100, n: 117.77, p: 46.24, k: 19.56, temperature: 23.99, humidity: 79.84, ph: 6.91, rainfall: 80.4 },
  { crop: "Cucumber (Kheera)", count: 14, n: 60, p: 60, k: 85, temperature: 28.39, humidity: 86.06, ph: 6.5, rainfall: 935.48 },
  { crop: "Drumstick (Moringa/Sahjan)", count: 14, n: 40, p: 20, k: 10, temperature: 27.76, humidity: 91.71, ph: 6.5, rainfall: 1713.08 },
  { crop: "Garlic (Lehsun)", count: 180, n: 50, p: 10, k: 60, temperature: 25.66, humidity: 87.04, ph: 5.5, rainfall: 965.94 },
  { crop: "Grapes", count: 100, n: 23.18, p: 132.53, k: 200.11, temperature: 23.85, humidity: 81.88, ph: 6.03, rainfall: 69.61 },
  { crop: "Horse Gram (Kulthi)", count: 272, n: 20, p: 60, k: 20, temperature: 26.41, humidity: 53.04, ph: 5.99, rainfall: 611.8 },
  { crop: "Jackfruit (Kathal)", count: 16, n: 75, p: 40, k: 50, temperature: 27.41, humidity: 83.27, ph: 4.95, rainfall: 1455.13 },
  { crop: "Jute", count: 100, n: 78.4, p: 46.86, k: 39.99, temperature: 24.96, humidity: 79.64, ph: 6.73, rainfall: 174.79 },
  { crop: "Kidney Beans (Rajma)", count: 100, n: 20.75, p: 67.54, k: 20.05, temperature: 20.12, humidity: 21.61, ph: 5.75, rainfall: 105.92 },
  { crop: "Lentil (Masoor)", count: 100, n: 18.77, p: 68.36, k: 19.41, temperature: 24.51, humidity: 64.8, ph: 6.93, rainfall: 45.68 },
  { crop: "Maize (Corn)", count: 100, n: 77.76, p: 48.44, k: 19.79, temperature: 22.39, humidity: 65.09, ph: 6.25, rainfall: 84.77 },
  { crop: "Mango", count: 100, n: 20.07, p: 27.18, k: 29.92, temperature: 31.21, humidity: 50.16, ph: 5.77, rainfall: 94.7 },
  { crop: "Moth Beans", count: 100, n: 21.44, p: 48.01, k: 20.23, temperature: 28.19, humidity: 53.16, ph: 6.83, rainfall: 51.2 },
  { crop: "Mung Bean (Green Gram/Moong)", count: 100, n: 20.99, p: 47.28, k: 19.87, temperature: 28.53, humidity: 85.5, ph: 6.72, rainfall: 48.4 },
  { crop: "Muskmelon (Kharbuja)", count: 100, n: 100.32, p: 17.72, k: 50.08, temperature: 28.66, humidity: 92.34, ph: 6.36, rainfall: 24.69 },
  { crop: "Lady Finger (Okra/Bhindi)", count: 32, n: 80, p: 10, k: 40, temperature: 28.11, humidity: 80.79, ph: 6.5, rainfall: 1160.56 },
  { crop: "Onion (Pyaaz)", count: 383, n: 120, p: 60, k: 65, temperature: 25.97, humidity: 81.81, ph: 6, rainfall: 782.7 },
  { crop: "Orange (Santra)", count: 100, n: 19.58, p: 16.55, k: 10.01, temperature: 22.77, humidity: 92.17, ph: 7.02, rainfall: 110.47 },
  { crop: "Papaya", count: 100, n: 49.88, p: 59.05, k: 50.04, temperature: 33.72, humidity: 92.4, ph: 6.74, rainfall: 142.63 },
  { crop: "Pigeon Peas (Tur/Arhar)", count: 100, n: 20.73, p: 67.73, k: 20.29, temperature: 27.74, humidity: 48.06, ph: 5.79, rainfall: 149.46 },
  { crop: "Pineapple (Ananas)", count: 24, n: 160, p: 40, k: 120, temperature: 24.94, humidity: 82.35, ph: 6.51, rainfall: 1752.7 },
  { crop: "Pomegranate", count: 100, n: 18.87, p: 18.75, k: 40.21, temperature: 21.84, humidity: 90.13, ph: 6.43, rainfall: 107.53 },
  { crop: "Potato (Aloo)", count: 461, n: 180, p: 60, k: 90, temperature: 23.85, humidity: 78.95, ph: 5, rainfall: 864.07 },
  { crop: "Pumpkin (Kaddu)", count: 7, n: 80, p: 50, k: 30, temperature: 27.65, humidity: 83.89, ph: 5.53, rainfall: 884.5 },
  { crop: "Radish (Mooli)", count: 11, n: 25, p: 100, k: 50, temperature: 26.76, humidity: 90.2, ph: 5.98, rainfall: 1138.42 },
  { crop: "Ragi (Finger Millet)", count: 293, n: 50, p: 40, k: 20, temperature: 27.15, humidity: 80.86, ph: 5.49, rainfall: 696.27 },
  { crop: "Rapeseed (Sarson)", count: 361, n: 50, p: 40, k: 20, temperature: 21.48, humidity: 67.94, ph: 5, rainfall: 174.87 },
  { crop: "Rice", count: 100, n: 79.89, p: 47.58, k: 39.87, temperature: 23.69, humidity: 82.27, ph: 6.43, rainfall: 236.18 },
  { crop: "Jowar (Sorghum)", count: 367, n: 80, p: 40, k: 40, temperature: 28.1, humidity: 83.69, ph: 5.5, rainfall: 569.59 },
  { crop: "Soybean (Soyabean)", count: 196, n: 20, p: 60, k: 20, temperature: 26.97, humidity: 48.44, ph: 5.5, rainfall: 825.09 },
  { crop: "Sunflower (Surajmukhi)", count: 362, n: 50, p: 60, k: 30, temperature: 26.81, humidity: 50.59, ph: 5.5, rainfall: 530.79 },
  { crop: "Sweet Potato (Shakarkandi)", count: 241, n: 90, p: 20, k: 120, temperature: 27.44, humidity: 81.54, ph: 5, rainfall: 1179.75 },
  { crop: "Tomato (Tamatar)", count: 43, n: 100, p: 40, k: 90, temperature: 26.98, humidity: 82.91, ph: 6, rainfall: 1105.01 },
  { crop: "Turmeric (Haldi)", count: 259, n: 25, p: 60, k: 100, temperature: 24.7, humidity: 80.86, ph: 5, rainfall: 1326.51 },
  { crop: "Watermelon", count: 100, n: 99.42, p: 17, k: 50.22, temperature: 25.59, humidity: 85.16, ph: 6.5, rainfall: 50.79 },
  { crop: "Wheat (Gehun)", count: 264, n: 60, p: 30, k: 30, temperature: 20.52, humidity: 69.7, ph: 6.5, rainfall: 146.75 },
];
